### ISSUE TITLE
id() always returns None on linux

### ISSUE THREAD

**Issue by Diggsey** [gimli-rs/findshlibs#28]
It's hardcoded here:
https://github.com/gimli-rs/findshlibs/blob/master/src/linux/mod.rs#L160-L162

This library is used by sentry which relies on this being set.

**Comment by philipc** [comment]
This seems like something you would have to get by opening the file and parsing the ELF headers, so I think it is outside the scope of this crate?

**Comment by Diggsey** [comment]
Possibly, in that case the method should probably be documented as such (especially given the crate only supports osx and linux to begin with)

**Comment by mitsuhiko** [comment]
I made a PR in #34 now which implements this without opening the file. The shared libraries are already mapped so the elf notes can be parsed from the section.

**Comment by philipc** [comment]
Fixed by #34
