### ISSUE TITLE
TargetSharedLibrary::name() empty for the executable itself on linux

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/findshlibs#31]

**Comment by philipc** [comment]
I think that's something the caller has to handle, for example see [backtrace-rs](https://github.com/alexcrichton/backtrace-rs/blob/d8ea02ec9d268a87450d337279e9e7683dafc081/src/symbolize/gimli.rs#L141-L150).

**Comment by bjorn3** [comment]
I didnt know that. Could it be documented?
