### ISSUE TITLE
Support Android and iOS

### ISSUE THREAD

**Issue by fzyzcjy** [gimli-rs/findshlibs#66]
Currently it seems not supported. Could you please provide some hints on how shouold I work on it to support them? Thanks!

**Comment by philipc** [comment]
iOS should work the same as macOS, based on what backtrace-rs does. So might just need some additional cfg checks.

**Comment by fzyzcjy** [comment]
Aha interesting!

* android: I will try now
* ios: looking forward to your release!

**Comment by philipc** [comment]
I don't develop for ios, so I can't test it. Yes, it should only need some cfgs. So a PR adding those cfgs would be welcome.

My reason for mentioning backtrace-rs is that it uses the same macOS APIs as this crate (`_dyld_get_image_header` etc), and includes the same code for macos and ios: https://github.com/rust-lang/backtrace-rs/blob/aec8f168d895043c358f0bceed20c70a03b7a8a0/src/symbolize/gimli.rs#L164-L171.

**Comment by fzyzcjy** [comment]
Aha sounds quite reasonable. I will make a PR soon!
